<?php 
if(! $this->identity()) {
    $aclRoleName = "guest";
} else {
    $aclRoleName = $this->identity()->getAclRoleEntity()->getAclRoleName();
}
?>


<div class="collapse navbar-collapse pull-left" id="navbar-collapse">
<ul class="nav navbar-nav">
<?php if($this->entitys->count() > 0): ?>
<?php foreach($this->entitys as $entity): ?>


<?php if($this->acl()->isAllowed($aclRoleName, $entity->getMenuRoute()) ): ?>

<?php if($entity->getMenuItemEntity()->count() > 0): ?>
<li class="dropdown <?php if($this->layout()->activeMenuItem == $entity->getMenuRoute()):?>active<?php endif;?>">
	 <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	 	<i class="<?php echo $entity->getMenuIcon(); ?>" aria-hidden="true"></i>
	 	<span><?php echo $this->translate($entity->getMenuName()); ?></span>
	 	<span class="caret"></span>
	 </a>
	 <ul class="dropdown-menu" role="menu">
	 <?php foreach($entity->getMenuItemEntity() as $menuItemEntity): ?>
	 	<li><a href="<?php echo $this->url($menuItemEntity->getMenuItemRoute()); ?>" title="<?php echo $this->translate($menuItemEntity->getMenuItemName()); ?>">
	 			<i class="<?php echo $menuItemEntity->getMenuItemIcon(); ?>" aria-hidden="true"></i> 
	 			<?php echo $menuItemEntity->getMenuItemName(); ?>
	 		</a>
	 	</li>
	 <?php endforeach;?>
	 </ul>
</li>
<?php else : ?>
<li class="<?php if($this->layout()->activeMenuItem == $entity->getMenuRoute()):?>active<?php endif;?>">
	<a href="<?php echo $this->url($entity->getMenuRoute()); ?>" title="<?php echo $this->translate($entity->getMenuName()); ?>">
		<i class="<?php echo $entity->getMenuIcon(); ?>" aria-hidden="true"></i> 
		<span><?php echo $this->translate($entity->getMenuName()); ?></span>
	</a>
</li>
<?php endif; ?>

<?php endif; ?>
<?php endforeach; ?>
<?php endif; ?>
</ul>
</div>