<?php
/**
* Pacific NM (https://www.pacificnm.com)
*
* @link      https://github.com/pacificnm/pnm for the canonical source repository
* @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
* @license
*/
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate("Application Menu"); ?> 
					<small><?php echo $this->entity->getMenuName(); ?></small>
				</h3>
				<div class="box-tools">
					<?php echo $this->deleteButton("menu-delete", array("id" => $this->entity->getMenuId())); ?>
					
					<?php echo $this->updateButton("menu-update", array("id" => $this->entity->getMenuId())); ?>
				</div>
			</div>
			<div class="box-body box-profile">
                <h3 class="profile-username text-center">
                	<?php echo $this->entity->getMenuName(); ?>
                </h3>
                <p class="text-muted text-center">
                	<?php echo $this->entity->getMenuRoute(); ?>
                </p>
                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Id"); ?>:</b>
                    	<?php echo $this->entity->getMenuId(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Name"); ?>:</b>
                    	<?php echo $this->entity->getMenuName(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Route"); ?>:</b>
                    	<?php echo $this->entity->getMenuRoute(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Icon"); ?>:</b>
                    	<?php echo $this->entity->getMenuIcon(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Location"); ?>:</b>
                    	<?php echo $this->entity->getMenuLocation(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Order"); ?>:</b>
                    	<?php echo $this->entity->getMenuOrder(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Active"); ?>:</b>
                    	<?php echo ($this->entity->getMenuActive() == 1 ? $this->translate("Yes") : $this->translate("No")) ; ?>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<?php echo $this->translate("Menu Items"); ?>
				</h3>
				<div class="box-tools">
                    <?php echo $this->createButton("menu-item-create", array(),
                        array("query" => array("menuId" => $this->entity->getMenuId()))); ?>
                </div>
			</div>
			<?php if($this->menuItemEntitys->count() == 0): ?>
			<div class="box-body">
				<div class="alert alert-info">
					<p>
						<i class="fa fa-info-circle" aria-hidden="true"></i> 
						<?php echo $this->translate("No menu items found"); ?>
					</p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body  no-padding">
				<table class="table table-bordered table-hover table-striped table-condensed">
					<thead>
						<tr>
							<th><?php echo $this->translate("Name");?></th>
							<th><?php echo $this->translate("Route"); ?></th>
							<th><?php echo $this->translate("Icon"); ?></th>
							<th><?php echo $this->translate("Order"); ?></th>
							<th><?php echo $this->translate("Active"); ?></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->menuItemEntitys as $entity): ?>
						<tr>
							<td>
								<a href="<?php echo $this->url("menu-item-view", array("id" => $entity->getMenuItemId())); ?>" title="<?php echo $this->translate("View")?>">
									<?php echo $entity->getMenuItemName();?>
								</a>
							</td>
							<td><?php echo $entity->getMenuItemRoute(); ?></td>
							<td><?php echo $entity->getMenuItemIcon(); ?></td>
							<td><?php echo $entity->getMenuItemOrder(); ?></td>
							<td><?php echo ($entity->getMenuItemActive() == 1 ? $this->translate("Yes"): $this->translate("No")); ?></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
			<?php endif; ?>
		</div>
	</div>
</div>